apiVersion: v1
kind: ServiceAccount
metadata:
  name: prefect-worker
  namespace: dataops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prefect-worker-role
  namespace: dataops
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/status"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prefect-worker-rolebinding
  namespace: dataops
subjects:
  - kind: ServiceAccount
    name: prefect-worker
    namespace: dataops
roleRef:
  kind: Role
  name: prefect-worker-role
  apiGroup: rbac.authorization.k8s.io
